global using Snebur;
global using Snebur.Dominio;
global using Snebur.Utilidade;
global using Snebur.Extensao;
global using System;
global using System.Linq;
global using System.Text.RegularExpressions;
global using System.Collections.Generic;
global using Newtonsoft.Json;