
-- Verificar configurações (opcional)
SELECT name, is_read_committed_snapshot_on, snapshot_isolation_state_desc
FROM sys.databases
WHERE name = 'DATABASE_NAME';
GO

-- IF snapshot_isolation_state_desc <> ON then

-- Mudar para SINGLE_USER
ALTER DATABASE [DATABASE_NAME]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

-- Habilitar ALLOW_SNAPSHOT_ISOLATION
ALTER DATABASE [DATABASE_NAME]
SET ALLOW_SNAPSHOT_ISOLATION ON;
GO

-- Habilitar READ_COMMITTED_SNAPSHOT
ALTER DATABASE [DATABASE_NAME]
SET READ_COMMITTED_SNAPSHOT ON;
GO

-- Mudar para MULTI_USER
ALTER DATABASE [DATABASE_NAME]
SET MULTI_USER;
GO

